### ISSUE TITLE
Multiple schemas feature not working

### ISSUE THREAD

**Issue by tomasz-nolberczak** [aldeed/meteor-collection2-core#29]
Multiple schemas feature not working. I have code as below:

```javascript
import { Meteor } from "meteor/meteor";
import SimpleSchema from 'simpl-schema';

Profiles = new Mongo.Collection('Profiles');

SchemaProfile = new SimpleSchema({
    userId: {
        type: String,
    },
    firstName: {
        type: String,
        optional: true,
    },
    lastName: {
        type: String,
        optional: true,
    },
    role: {
        type: Number,
        allowedValues: [UserGroup.EMPLOYEE, UserGroup.EMPLOYER, UserGroup.ADMINISTRATOR]
    },
});

SchemaEmployeeProfile = SchemaProfile.extend({
    daysRemaining: {
        type: Number,
        min: 0,
        defaultValue: 20,
    },
    position: {
        type: String,
    }
});

SchemaEmployerProfile = SchemaProfile.extend({
    someOtherField: {
        type: String,
    }
});

Profiles.attachSchema(SchemaEmployeeProfile, {selector: {role: UserGroup.EMPLOYEE}});
Profiles.attachSchema(SchemaEmployerProfile, {selector: {role: UserGroup.EMPLOYER}});
```

Trying to create new item in Profiles collection:

```javascript
const profileId = Profiles.insert({
	userId: userId,
	role: UserGroup.EMPLOYER,
}, { selector: { role: UserGroup.EMPLOYER }});
```

Error:

```bash
Exception while invoking method 'employerCreate' Error: position is required
at getErrorObject (packages/aldeed:collection2-core/collection2.js:453:15)
at [object Object].doValidate (packages/aldeed:collection2-core/collection2.js:435:13)
at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2-core/collection2.js:187:25)
at [object Object].Meteor.methods.employerCreate (imports/server/methods/employers.js:21:30)
at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
at packages/ddp-server/livedata_server.js:719:19
at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
at packages/ddp-server/livedata_server.js:717:40
at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
at packages/ddp-server/livedata_server.js:715:46
Sanitized and reported to the client as: position is required [400]
```

So, it validates against `SchemaEmployeeProfile`, not `SchemaEmployerProfile`, as it should.

**Please, fix it.**

**Comment by jshimko** [comment]
From the README:

> **Alternatively**, you can pass a selector option when inserting to choose which schema to use:
```
Products.insert({ title: 'This is a product' }, { selector: { type: 'simple' } });
```
(source) https://github.com/aldeed/meteor-collection2-core#attaching-multiple-schemas-to-the-same-collection

Note the word "alternatively".  You are doing _both_ methods of setting the selector when only one of them is required.  So I'd start there by changing your insert to...
```js
const profileId = Profiles.insert({
  userId: userId,
  role: UserGroup.EMPLOYER,
});
```

The `role` field was already set as the selector when you defined the schema.

**Comment by aldeed** [comment]
@tomasz-nolberczak Is this resolved? @jshimko is correct, although it seems like it should work anyway. I'd also make sure you have the latest collection2-core package.

**Comment by hems** [comment]
We are using the latest collection2-core package and 'simple-schema' from NPM.

We used to have attachSchema working perfectly on previous meteor app, but with the new one with Meteor 1.7 attaching multiple schemas is over-writing the original schema?
