### ISSUE TITLE
Error saying that a value is required even though the value is provided

### ISSUE THREAD

**Issue by ignacy130** [aldeed/meteor-collection2-core#41]
This is my Schema:
```
Schema.UserProfile = new SimpleSchema({
    name: {
        type: String,
        label: "Name",
        optional: false
    },
...
Schema.User = new SimpleSchema({
    userProfile: {
        type: Schema.UserProfile,
        optional: false
    },
```
and insert method:
```
var profile = {
        name: 'Sacha Greif',
        email: "sacha@example.com",
        phone: 555999000
    };
    var adminId = Accounts.createUser({
        userProfile: profile,
...
```
but I get error:
```
Error: Name is required
    at getErrorObject (packages/aldeed:collection2-core/collection2.js:453:15)
    at [object Object].doValidate (packages/aldeed:collection2-core/collection2.js:435:13)
    at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2-core/collection2.js:187:25)
    at AccountsServer.Ap.insertUserDoc (packages/accounts-base/accounts_server.js:1325:25)
    at createUser (packages/accounts-password/password_server.js:1050:25)
    at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1119:10)
    at meteorInstall.server.setup.fixtures.adminFixture.js (server/setup/fixtures/adminFixture.js:22:28)
    at fileEvaluate (packages\modules-runtime.js:333:9)
    at require (packages\modules-runtime.js:228:16)
```

Is it bug or I'm doing something wrong? It was working with old (not core) aldeed:simple-schema and collection2

I get the same bug on first level (not nested) fields.

`Meteor.users.simpleSchema().validate(u);` does not throw any errors

**Comment by ignacy130** [comment]
Nevermind, I forgot that `Accounts.createUser` function does not use all the fields provided in argument, so name was simply not provided. Sorry, can be closed.

**Comment by ignacy130** [comment]
Also
```
var profile = {
        name: 'Sacha Greif',
        email: "sacha@example.com",
        phone: 555999000,
        VAT: true
    };
    var u = {
        // userProfile: profile,
        username: "sacha231",
        password: "123456",
        savedPosts: [],
        notifications: [],
        createdAt: new Date()
    };
    Meteor.users.simpleSchema().validate(u);
    const validationContext = Schema.User.newContext();
    validationContext.validate(u);

    console.log(validationContext.isValid());
    console.log(validationContext.validationErrors());
    var adminId = Meteor.users.insert(u);
```
returns:
```
true
[]
Application has errors
```
and in the browser
```
Error: Name is required
```

**Comment by aldeed** [comment]
Not sure, but if there is a default/autoValue for anything in the profile, it might be creating the `profile` object in order to add that default, or an accounts package might be adding something to `profile`. Once the profile object is present, it would then complain if there is no `name` property in it.
