### ISSUE TITLE
MongoError: connection to DB timed out

### ISSUE THREAD

**Issue by 416serg** [aldeed/meteor-collection2-core#42]
I have an app that gets some information from an API call and then uploads the result to a collection. 

I first gather all the right documents in an array then do `array.map(object => Collection.insert(object));`

But it throws the error below for an array of about 70 objects. Should I `setTimeout` on the map to insert the objects every x milliseconds or is it caused by something else?

```
Exception in setTimeout callback: MongoError: connection 4 to aws-us-east-1-portal.23.dblayer.com:15676 timed out
    at Object.Future.wait (/var/app/current/node_modules/fibers/future.js:449:15)
    at null.<anonymous> (packages/meteor.js:213:24)
    at null.MongoConnection.(anonymous function) [as insert] (meteor://ðŸ’»app/packages/mongo/mongo_driver.js:778:49)
    at null.insert (meteor://ðŸ’»app/packages/mongo/collection.js:524:37)
    at null.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:232:19)
    at meteor://ðŸ’»app/imports/startup/server/analytics.js:319:13
    at null._.extend.withValue (packages/meteor.js:1122:17)
    at packages/meteor.js:445:45
    at runWithEnvironment (packages/meteor.js:1176:24)
    - - - - -
    at Function.MongoError.create (/var/app/current/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:29:11)
    at TLSSocket.<anonymous> (/var/app/current/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:186:20)
    at TLSSocket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket.Socket._onTimeout (net.js:332:8)
    at _runOnTimeout (timers.js:524:11)
    at _makeTimerTimeout (timers.js:515:3)
    at Timer.unrefTimeout (timers.js:584:5)
```

**Comment by aldeed** [comment]
This would be an issue to report in the Meteor repo
