### ISSUE TITLE
Problem with multi attacheSchema()?

### ISSUE THREAD

**Issue by thearabbit** [aldeed/meteor-collection2-core#55]
I try to create `soft remove` library
Collection
```js
import {Mongo} from 'meteor/mongo';
import SimpleSchema from 'simpl-schema';

const AccountTypes = new Mongo.Collection('acc_accountTypes');

AccountTypes.schema = new SimpleSchema({
    code: {
        type: String,
        unique: true
    },
    name: {
        type: String,
        unique: true
    },
    nature: {
        type: String,
        allowedValues: ['Asset', 'Liability', 'Equity', 'Revenue', 'Expense']
    },
    status: {
        type: String,
    },
    memo: {
        type: String,
        optional: true
    }
});

AccountTypes.attachSchema(AccountTypes.schema);
export default AccountTypes;
```
Library
```js
// Soft Remove
CollectionExtensions.addPrototype('softRemove', function (selector = {}) {
    let self = this;
    const schema = new SimpleSchema({
        removed: Boolean,
        removedAt: Date,
        removedBy: String
    });
    self.attachSchema(schema, {selector: {type: 'softRemove'}});

    return self.direct.update(
        selector,
        {
            $set: {
                // selector: {type: 'softRemove'}, // where to put this
                removed: true,
                removedAt: new Date(),
                removedBy: Meteor.userId()
            }
        },
        {multi: true},
        (error, num) => {
            if (num) {
                console.log('soft remove');
            }
        }
    );
});
```
Please help me

**Comment by aldeed** [comment]
You should put `selector: {type: 'softRemove'}` in the options, where `multi: true` is.

**Comment by thearabbit** [comment]
Thanks it work fine 👍

**Comment by thearabbit** [comment]
Excuse me, sometimes get error when Insert Data
```
Exception while invoking method 'acc.insertAccountType' TypeError: Cannot read property 'namedContext' of null
I20180203-19:53:56.157(7)?     at doValidate (packages/aldeed:collection2/collection2.js:284:32)
I20180203-19:53:56.157(7)?     at ns.Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:195:14)
I20180203-19:53:56.159(7)?     at MethodInvocation.run (imports/modules/acc/api/account-types/methods.js:54:33)
I20180203-19:53:56.159(7)?     at ValidatedMethod._execute (packages/mdg:validated-method/validated-method.js:93:12)
I20180203-19:53:56.160(7)?     at MethodInvocation.acc.insertAccountType (packages/mdg:validated-method/validated-method.js:54:23)
I20180203-19:53:56.160(7)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20180203-19:53:56.161(7)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20180203-19:53:56.162(7)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
I20180203-19:53:56.162(7)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20180203-19:53:56.163(7)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
I20180203-19:53:56.172(7)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20180203-19:53:56.173(7)?     at new Promise (<anonymous>)
I20180203-19:53:56.173(7)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20180203-19:53:56.174(7)?     at packages/ddp-server/livedata_server.js:559:43
```

**Comment by thearabbit** [comment]
And then I tried remove `selector: {type: 'softRemove'}`
But get error
``
{ Error: Removed is required in acc_accountTypes insert
```
Please help me
