### ISSUE TITLE
Attach schema to Meteor.users: cannot create users

### ISSUE THREAD

**Issue by anthonyboutinov** [aldeed/meteor-collection2-core#9]
I get this error message:
```
Exception while invoking method 'ATCreateUserServer' Error: Created at must be a Date
```

Schema:
```javascript
const UserSchema = new SimpleSchema({
  createdAt: {
    type: Date
  },
  //...
});
Meteor.users.attachSchema(UserSchema);
```

Full exception report:
```
Exception while invoking method 'ATCreateUserServer' Error: Created at must be a Date
I20161207-22:59:39.868(3)?     at getErrorObject (packages/aldeed_collection2-core.js:480:15)
I20161207-22:59:39.868(3)?     at [object Object].doValidate (packages/aldeed_collection2-core.js:462:13)
I20161207-22:59:39.868(3)?     at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:214:25)
I20161207-22:59:39.869(3)?     at AccountsServer.Ap.insertUserDoc (packages/accounts-base/accounts_server.js:1326:25)
I20161207-22:59:39.869(3)?     at _createUser (packages/accounts-password/password_server.js:1009:25)
I20161207-22:59:39.869(3)?     at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1078:10)
I20161207-22:59:39.870(3)?     at [object Object].Meteor.methods.ATCreateUserServer (packages/useraccounts_core.js:1294:27)
I20161207-22:59:39.870(3)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1712:12)
I20161207-22:59:39.871(3)?     at packages/ddp-server/livedata_server.js:711:19
I20161207-22:59:39.871(3)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20161207-22:59:39.875(3)? Sanitized and reported to the client as: Created at must be a Date [400]
```

I can't figure out how to fix it. Please, help!

**Comment by anthonyboutinov** [comment]
I've spent hours and hours over this error, and... This is silly))

So, if anyone find themselves encountering this error, check if your `UserProfileSchema` has `createdAt` field. If it does, **remove** it. It doesn't make sense anyway, since it's a subdocument.

I hope this helps somebody. =)
